### ISSUE TITLE
Training portal ideas

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#27]
Hey all! 

We've collectively had a bunch of great ideas for the training portal. Let's use this issue to discuss and share our ideas - each comment counts as a contribution for Outreachy. 🌟

**Comment by Persdre** [comment]
Let me be the first one haha.
1. change the layout: add each link on the page a small window to roughly summarize the content, such as the YouTube homepage.
2. give detailed content in every part: now there is not enough explanation in every link. Besides pictures, we can add more concrete guides to it.
3. more lively: now it seems too monotomous. Maybe we can change its color scheme and font style.

**Comment by Persdre** [comment]
<img width="890" alt="Screenshot 2020-03-18 at 12 34 55 AM" src="https://user-images.githubusercontent.com/35624031/76879325-10e27c80-68b1-11ea-8684-2b80c51e68b0.png">
just as I said, the picture is not clear enough.

**Comment by wintermornings00** [comment]
1. Table of Contents- Changing the background color to make it more noticeable. Also taking care of the white space between the headings.
2. Maybe include a short introduction to what the page does before Contents.
3. Under the tutorials section we can change the text color of answers or indent it to make it more readable.
4. We can get rid of the underlines in the sub headings.

**Comment by anushkajha** [comment]
1)Changing the way the content is organised could be very helpful especially for first time users .
 We can  divide  resources available in sections (introductory ,advance)
Also  group all the resources(video,slides ,links) of a particular topic together  under a well defined heading  that   would make it  easier for the user to search resources about interrelated topics.
changes in styling would be required so that users can properly differentiate between different sections.

2)  We should provide both video as well as written tutorial for topics we are covering(for as many topics as possible)  because different people have different learning style some might prefer videos and other might prefer written content

**Comment by Persdre** [comment]
> 1)Changing the way the content is organised could be very helpful especially for first time users .
> We can divide resources available in sections (introductory ,advance)
> Also group all the resources(video,slides ,links) of a particular topic together under a well defined heading that would make it easier for the user to search resources about interrelated topics.
> changes in styling would be required so that users can properly differentiate between different sections.
> 
> 1. We should provide both video as well as written tutorial for topics we are covering(for as many topics as possible)  because different people have different learning style some might prefer videos and other might prefer written content

en, I am not clear how to make a video.  Do you mean screen recording?

**Comment by SiSousa** [comment]
it is my first time here and i want to help... i am having some ideas now but lets start:
1-There would be a good idea have an search field in tutorials section of intermine website, so the user could search for a tutorial filtering by level(ex: begginers, advanced) and the option of also filtering by programming language(ex: python, R)
2-It would be a good idea have an topic only for exercicies so the user could better understand what he learnt on the tutorials or see a pratical exemple of using (when i start to learn a new technology/programming language i have this dificult so i guess there other people with the same).
i hope i've help, i accept advices, i hope i can help with the project.

**Comment by ddada24** [comment]
1. There can be a training/Tutorial link in the top right corner of Intermine home page, where there is "Biologists, Developers, contacts and resources"  this will help a first time visitor on the site to find it easy familiarizing themselves to the page and also carry out the required activities on Intermine as the will see what will guide them at their first glance at the page. The Hugo mainroad theme can be adopted for this
2. Everything Tutorials, documentation, videos and training can be arranged inside a link (the link created above) and not scattered in different links such as : the Biologists link has the Tutorials and videos but arranged according to the Intermine registries and bluegene apps. Then, the description of each video link and documentation files should be properly written.

**Comment by anushkajha** [comment]
> en, I am not clear how to make a video. Do you mean screen recording?

@Persdre yes. screen recording would be used to make demo videos (you can record audio of the instruction simultaneously in screen recording).
also rather than making a long tutorial we can divide it into small modules where each module would contain a demo video and related written material .

**Comment by anushkajha** [comment]
@SiSousa i am  not sure i understood it right or not but i guess in point 2 you mean that we should add some practice exercise for the user. 
i think it's a nice idea we can add all the learning resources and practice problem in a module. 

also i think we can have something similar to the format of Coursera courses where you have a milestone to track your progress in tutorial .

**Comment by corine-donfack** [comment]
Hello here!!!
The training page should be displayed more interractif and eye catching. The design should be made enticing enough to give the user the will to lesrn more. I have  three main ideas as to how to make the training section better (some already been raised by my smart mates - will say it using my words though)

- we could separate the tutorials page in the general section according to levels. Like we could have tuto section for;
.dummies
.intermediate level and 
.advanced( where the pros can relate)😅

- now in every section especially for dummies, we should have tutos in the form of videos (prefarably linked to youtube), text and even links to ebooks(why not) so everyone can choose the learning style he or she prefers.

- and lastly why not add a life video chat section to speak with an expert (in case one is online)  to get clearifications as to what a user is learning at the moment.

**Comment by Persdre** [comment]
> > en, I am not clear how to make a video. Do you mean screen recording?
> 
> @Persdre yes. screen recording would be used to make demo videos (you can record audio of the instruction simultaneously in screen recording).
> also rather than making a long tutorial we can divide it into small modules where each module would contain a demo video and related written material .

good idea! I think it can be a main improvent in this summer.

**Comment by MinervaLong** [comment]
Hello everyone, your ideas in relation to the tutorials are great!

I've been focusing more on the templates and presentations on the website. I think that the Developers section is pretty well organized and has a clear content description so doing the same with the Biologist section could be nice, this way the style is coherent. Then the tutorials could be implemented in a Hugo template similar to:

[Learn template](https://themes.gohugo.io/hugo-theme-learn/)

[Docuapi template](https://themes.gohugo.io/docuapi/) This template has an option to switch between languages.

[Docsy template](https://example.docsy.dev/docs/) This template has an option to value the tutorial content.

In my view, Intermine learning materials should be in one place instead of multiple websites and in case of external resources like TargetMine tutorial it could be indicated it.

**Comment by ddada24** [comment]
> Hello here!!!
> The training page should be displayed more interractif and eye catching. The design should be made enticing enough to give the user the will to lesrn more. I have three main ideas as to how to make the training section better (some already been raised by my smart mates - will say it using my words though)
> 
> * we could separate the tutorials page in the general section according to levels. Like we could have tuto section for;
>   .dummies
>   .intermediate level and
>   .advanced( where the pros can relate)sweat_smile
> * now in every section especially for dummies, we should have tutos in the form of videos (prefarably linked to youtube), text and even links to ebooks(why not) so everyone can choose the learning style he or she prefers.
> * and lastly why not add a life video chat section to speak with an expert (in case one is online)  to get clearifications as to what a user is learning at the moment.

@corine-donfack, great comment! There can also be a link for On-site trainings for users who are interested,  venue can be determined by the Intermine group or interested users can invite Expert(s) to train them at their location (Travel Expenses on the user).

**Comment by corine-donfack** [comment]
@ddada24 that sounds nice too (the onsite idea) why not?

**Comment by SiSousa** [comment]
@anushkajha hi, yes this is the point, these exercises could be in a separate section inside the training portal, there it would also be awesome if the users could check the progress they are doing how you mentioned, and i also have an idea that the tutorials also could be rating by the users but i dont know... i am very excited to work in the project!

**Comment by tinycosmos** [comment]
> Hey all!
> 
> We've collectively had a bunch of great ideas for the training portal. Let's use this issue to discuss and share our ideas - each comment counts as a contribution for Outreachy. 🌟

Hi everyone
I appreciate the idea presented by everyone of improving the aesthetics of the website. Well I would also like to suggest some of the issues that i noticed could be improved in a hope to improve usability of the site:

1. Starting from the very top navbar:
    - Appreciate the idea of using [doormat navigation](https://www.nngroup.com/articles/footers/?lm=ten-usability-heuristics&pt=article) but it could be implemented in a better way. However the four menus listed here could be aesthetically improved.
    - The Options listed must be minimal, as every extra bit of information competes with the list items diminishing the relative visibility. ([#8](https://www.nngroup.com/articles/ten-usability-heuristics/))
    - I noticed we are using the [new window icon](https://www.google.com/search?q=new+window+icon&rlz=1C1CHBF_enIN853IN853&sxsrf=ALeKk01_0oGO_1iFGuRo322AgfN4BHlT5A:1584546202521&tbm=isch&source=iu&ictx=1&fir=rHYNIGlO2ZoQgM%253A%252CX7FJllfSkW3RmM%252C_&vet=1&usg=AI4_-kRNibXk6BmDI_tXg3ImrWZKlUNiNw&sa=X&ved=2ahUKEwi365_MrqToAhVafisKHS1iCTsQ9QEwAHoECAsQIQ#imgrc=rHYNIGlO2ZoQgM:) in several places on the site, but they are serving as mixed-up [mental models](https://www.nngroup.com/articles/mental-models/) i.e, the icon specifies that link would open in a new tab, but it does not (not serves the function what it is meant for).
    - When site size is reduced, in the list i can notice there is no hover effect in it.

2. Coming to the Introduction part
    - Agree with the idea of linking some videos or short tutorials that would help new users to catch up with the website. These videos may include short tutorials on what site is all about and what data can be accessed from which section.
    - Again aesthetics can be improved to a great extent, I’ll present some design on this one. I noticed some of the important data that users are suppressed in the site, we can highlight them in a way that it catches the attention. For eg, installation open source description, contribution guide.
    - The list of the mines listed can be improved if we add some short description to all of ‘em. Also a question here...why are the buttons having colored underline? Does it imply something?
    - The idea of involving the user through ‘which Intermine is for you’ section is really good, but again being at the bottom of the site reduces it’s effectiveness.

3. Footer! Last but not the least.
    - Footer is a place where the users ends up scrolling when they’re lost, causing it to leave an everlasting impression. Even the most mundane and utilitarian section of interface can make the biggest impact!
    - Again [here](https://www.nngroup.com/articles/footers/?lm=ten-usability-heuristics&pt=article) aesthetics could be improved and content could be made more minimalist along with improving the mixed up mental model (back-end issue).

There are many small back-end issues like this, is it okay for me to open these issues for others to resolve it?

So this was the analysis I made keeping the design theories in mind. Would love to have some suggestions and feedback!

**Comment by SiSousa** [comment]
@tinycosmos hi, i found your observations very interesting, especially what you pointed at 2.4 about the idea of involving the user in the section that is located in the bottom, this is something i would like to help, so will you open these issues for others who have interested in solve? thanks for any suggestion or advice.

**Comment by tinycosmos** [comment]
> @tinycosmos hi, i found your observations very interesting, especially what you pointed at 2.4 about the idea of involving the user in the section that is located in the bottom, this is something i would like to help, so will you open these issues for others who have interested in solve? thanks for any suggestion or advice.

Hi there!
I would definitely open the issue once i propose some design which I'm working on currently for the website.
Thanks and let me know if you have some suggestions to increase user participation.

**Comment by SiSousa** [comment]
> > @tinycosmos hi, i found your observations very interesting, especially what you pointed at 2.4 about the idea of involving the user in the section that is located in the bottom, this is something i would like to help, so will you open these issues for others who have interested in solve? thanks for any suggestion or advice.
> 
> Hi there!
> I would definitely open the issue once i propose some design which I'm working on currently for the website.
> Thanks and let me know if you have some suggestions to increase user participation.

thanks for answer, i think what you pointed are very useful and how i said, i would like to help, especially in the 2.4 point if it would be possible, i have some ideias too, like implement an search field where users can search tutorials by level(ex: begginer, hard) and also filtering by programming language(ex:python, R) and to improve the section to pratical exercices where users can see in pratical what they learnt in the tutorials maybe how one participant suggest in my comment by making users check their progress, and i think that have an way to rating the tutorials would be a good idea, open for advices, thanks for help.

**Comment by corine-donfack** [comment]
> > Hey all!
> > We've collectively had a bunch of great ideas for the training portal. Let's use this issue to discuss and share our ideas - each comment counts as a contribution for Outreachy. star2
> 
> Hi everyone
> I appreciate the idea presented by everyone of improving the aesthetics of the website. Well I would also like to suggest some of the issues that i noticed could be improved in a hope to improve usability of the site in every possible way i can:
> 
> 1. Starting from the very top navbar:
>    
>    * Appreciate the idea of using [doormat navigation](https://www.nngroup.com/articles/footers/?lm=ten-usability-heuristics&pt=article) but it could be implemented in a better way. However the four menus listed here could be aesthetically improved.
>    * The Options listed must be minimal, as every extra bit of information competes with the list items diminishing the relative visibility. ([#8](https://www.nngroup.com/articles/ten-usability-heuristics/))
>    * I noticed we are using the [new window icon](https://www.google.com/search?q=new+window+icon&rlz=1C1CHBF_enIN853IN853&sxsrf=ALeKk01_0oGO_1iFGuRo322AgfN4BHlT5A:1584546202521&tbm=isch&source=iu&ictx=1&fir=rHYNIGlO2ZoQgM%253A%252CX7FJllfSkW3RmM%252C_&vet=1&usg=AI4_-kRNibXk6BmDI_tXg3ImrWZKlUNiNw&sa=X&ved=2ahUKEwi365_MrqToAhVafisKHS1iCTsQ9QEwAHoECAsQIQ#imgrc=rHYNIGlO2ZoQgM:) in several places on the site, but they are serving as mixed-up [mental models](https://www.nngroup.com/articles/mental-models/) i.e, the icon specifies that link would open in a new tab, but it does not (not serves the function what it is meant for).
>    * When site size is reduced, in the list i can notice there is no hover effect in it.
> 2. Coming to the Introduction part
>    
>    * Agree with the idea of linking some videos or short tutorials that would help new users to catch up with the website. These videos may include short tutorials on what site is all about and what data can be accessed from which section.
>    * Again aesthetics can be improved to a great extent, I’ll present some design on this one. I noticed some of the important data that users are suppressed in the site, we can highlight them in a way that it catches the attention. For eg, installation open source description, contribution guide.
>    * The list of the mines listed can be improved if we add some short description to all of ‘em. Also a question here...why are the buttons having colored underline? Does it imply something?
>    * The idea of involving the user through ‘which Intermine is for you’ section is really good, but again being at the bottom of the site reduces it’s effectiveness.
> 3. Footer! Last but not the least.
>    
>    * Footer is a place where the users ends up scrolling when they’re lost, causing it to leave an everlasting impression. Even the most mundane and utilitarian section of interface can make the biggest impact!
>    * Again [here](https://www.nngroup.com/articles/footers/?lm=ten-usability-heuristics&pt=article) aesthetics could be improved and content could be made more minimalist along with improving the mixed up mental model (back-end issue).
> 
> There are many small back-end issues like this, is it okay for me to open these issues for others to resolve it?
> 
> So this was the analysis of the existing website I made keeping the design theories in mind. Would love to have some suggestions and feedback!

Smart for the footer! Its true that thats were you roam around when you start getting lost. Improving it should really be a main point of concern. Now the 'HOW?' Question

**Comment by tinycosmos** [comment]
> > > Hey all!
> > > We've collectively had a bunch of great ideas for the training portal. Let's use this issue to discuss and share our ideas - each comment counts as a contribution for Outreachy. star2
> > 
> > 
> > Hi everyone
> > I appreciate the idea presented by everyone of improving the aesthetics of the website. Well I would also like to suggest some of the issues that i noticed could be improved in a hope to improve usability of the site in every possible way i can:
> > 
> > 1. Starting from the very top navbar:
> >    
> >    * Appreciate the idea of using [doormat navigation](https://www.nngroup.com/articles/footers/?lm=ten-usability-heuristics&pt=article) but it could be implemented in a better way. However the four menus listed here could be aesthetically improved.
> >    * The Options listed must be minimal, as every extra bit of information competes with the list items diminishing the relative visibility. ([#8](https://www.nngroup.com/articles/ten-usability-heuristics/))
> >    * I noticed we are using the [new window icon](https://www.google.com/search?q=new+window+icon&rlz=1C1CHBF_enIN853IN853&sxsrf=ALeKk01_0oGO_1iFGuRo322AgfN4BHlT5A:1584546202521&tbm=isch&source=iu&ictx=1&fir=rHYNIGlO2ZoQgM%253A%252CX7FJllfSkW3RmM%252C_&vet=1&usg=AI4_-kRNibXk6BmDI_tXg3ImrWZKlUNiNw&sa=X&ved=2ahUKEwi365_MrqToAhVafisKHS1iCTsQ9QEwAHoECAsQIQ#imgrc=rHYNIGlO2ZoQgM:) in several places on the site, but they are serving as mixed-up [mental models](https://www.nngroup.com/articles/mental-models/) i.e, the icon specifies that link would open in a new tab, but it does not (not serves the function what it is meant for).
> >    * When site size is reduced, in the list i can notice there is no hover effect in it.
> > 2. Coming to the Introduction part
> >    
> >    * Agree with the idea of linking some videos or short tutorials that would help new users to catch up with the website. These videos may include short tutorials on what site is all about and what data can be accessed from which section.
> >    * Again aesthetics can be improved to a great extent, I’ll present some design on this one. I noticed some of the important data that users are suppressed in the site, we can highlight them in a way that it catches the attention. For eg, installation open source description, contribution guide.
> >    * The list of the mines listed can be improved if we add some short description to all of ‘em. Also a question here...why are the buttons having colored underline? Does it imply something?
> >    * The idea of involving the user through ‘which Intermine is for you’ section is really good, but again being at the bottom of the site reduces it’s effectiveness.
> > 3. Footer! Last but not the least.
> >    
> >    * Footer is a place where the users ends up scrolling when they’re lost, causing it to leave an everlasting impression. Even the most mundane and utilitarian section of interface can make the biggest impact!
> >    * Again [here](https://www.nngroup.com/articles/footers/?lm=ten-usability-heuristics&pt=article) aesthetics could be improved and content could be made more minimalist along with improving the mixed up mental model (back-end issue).
> > 
> > There are many small back-end issues like this, is it okay for me to open these issues for others to resolve it?
> > So this was the analysis of the existing website I made keeping the design theories in mind. Would love to have some suggestions and feedback!
> 
> Smart for the footer! Its true that thats were you roam around when you start getting lost. Improving it should really be a main point of concern. Now the 'HOW?' Question

yeah I'm currently working on this one, just researching on how, where and in which way to present data. I'll come up with the low fidelity frames for the website soon. 
Till then ideas and suggestions are most welcomed :)

**Comment by corine-donfack** [comment]
@tinycosmos will think about it too

**Comment by NorahKiggundu** [comment]
I have not got to the training part yet. First I will say InterMine is very informative for beginners to open source projects. I have so far read the open source guide to submitting contributions and I suggest we change make the following changes to make the work easier to read and navigate through:

1. In section 1: The reasons for contributing to open source can be enumerated as 1,2,3,4 and contain shorter and more clearer headings.
2.  In section 2: What it means to contribute. The sub headings can be changed from being questions to short and clear headings. This can also be tabulated to reduce the length of the page. 
3. The two reviews from Bretcannon and orta can be merged into a carousel that slide shows them. This would reduce the length of the page.  

I am wondering if I can work on this and if there is anybody else interested that I can work with. I saw at the bottom of the page that it is possible to contribute to it.

**Comment by SiSousa** [comment]
hi everyone, again.
I was exploring the tutorials section on the intermine website and having ideas to work, i think it would be a good idea separe the content into topics just like exercicies, workshops and videos in a way more dinamic as i comment before maybe grouping by programming language(ex:python, R) or by level(ex:begginer,hard), and maybe in the workshop topic maybe would be a good idea make it more eye catching and intutive  by add a twitter icon with the respective link and a calendar icon with the link to the events to make it more clear and intutive to the users, open to advices and suggestions.

**Comment by tinycosmos** [comment]
@SiSousa @NorahKiggundu guys please do mention the link to the site you are referring to, that would be of great help!

**Comment by TakorLucila** [comment]
(http://intermine.org) with respect to this site, i can say it is too crowded, there is a lot of things to read and check out just by visiting or entering the page.
also, the search bar "what intermine is for you" at the bottom of the page isn't really the best. i think i should be at the top so people visiting can be redirected immediately to what theyre really in search of

**Comment by TakorLucila** [comment]
the intermine.org site should be decongested and the site should have a separate page for tutorials

**Comment by TakorLucila** [comment]
with respect to the open source guide on how to submit a contribution, i think its to lengthy, its very explicit though but it can be broken down to shorter but explicit points. the resources linked to it are quite educative

**Comment by TakorLucila** [comment]
i also think that when an issue has been solved and merged, the mentors should close it so we don't go commenting on them and trying to work on them like the python tutorials

**Comment by SiSousa** [comment]
> @SiSousa @NorahKiggundu guys please do mention the link to the site you are referring to, that would be of great help!

Hi, okay, i was referring to this part of the website: http://intermine.org/tutorials/   open to suggestions and advices.

**Comment by anshukaira** [comment]
hi. you people really have great observations and your comments for the training portal are too good but what I have noticed that whenever I open the tutorial page I dont get any icon on the browser tab. I was wondering that is it happening in my browser or yours too? 
Now I really liked everyone's idea...
I guess working on more spacing and readability of the content would be good by changing the text formats and adding some pictures maybe? 
We can add more links and description. And I believe that other peoples comments are really very reliable. I would like to work on any issue that gets open for this website.
I am still just checking things and exploring. 
hope soon i ll come with some good idea

**Comment by Anu-Ranjan** [comment]
@yochannah Are we talking about this website? http://intermine.org/tutorials/. Please let me know so that I can contribute.

**Comment by Persdre** [comment]
Yes!

**Comment by guptadiksha307** [comment]
Hi there!!
1.) In addition to what @anushkajha and @SiSousa said, it's absolutely a great idea to provide video tutorials and practice sessions (for as many topics as possible) because most of the users prefer learning from videos rather than reading the whole content. But, I think it will become more cumbersome to have video and written tutorials for every topic. We can have some written tutorials or practice sheets(maybe quizzes or short notes) in pdf or any other formats to download.
2.) we can also add functionality to allow people to rate tutorials using Google Forms. I'm currently working on this and soon create an issue regarding this. Any changes and suggestions are always welcomed :)
3.) when I was going through the Intermine homepage after cloning the project in my local machine, I found a small issue that the link-"https://twitter.com/intermineorg" is not highlighted.
![image](https://user-images.githubusercontent.com/53967592/77505734-f9dff380-6e89-11ea-9ecc-b8ffb6ecfd40.png)
whereas when I opened "http://intermine.org/tutorials/", the link is highlighted.
![image](https://user-images.githubusercontent.com/53967592/77505828-37dd1780-6e8a-11ea-9709-4c038da430eb.png)
So I want to ask do I have to make changes in the project also? @yochannah

**Comment by SiSousa** [comment]
@guptadiksha307 hi, as i commented before there's a good idea to have a section to the pratical exercicies, i am currently working to organize the content in the tutorials page and group them into levels and similar topics to make it simpler and more intuitive to the users, i liked to much that you suggest to put some written materials and pdfs, especially the quizzes! ah, i really loved that you said that you are working in a way to make possible the idea of rating the tutorials, i commented about it but i didnt find a way to make it possible... but thats a issue that i would like to help, sucess, i am open to suggestions.

**Comment by yochannah** [comment]
@SiSousa 

>     1. There can be a training/Tutorial link in the top right corner of Intermine home page, where there is "Biologists, Developers, contacts and resources"  this will help a first time visitor on the site to find it easy familiarizing themselves to the page and also carry out the required activities on Intermine as the will see what will guide them at their first glance at the page. The Hugo mainroad theme can be adopted for this

could you share a demo of the theme? I'm quite fond of the current intermine theme. 

> 
>     2. Everything Tutorials, documentation, videos and training can be arranged inside a link (the link created above) and not scattered in different links such as : the Biologists link has the Tutorials and videos but arranged according to the Intermine registries and bluegene apps. Then, the description of each video link and documentation files should be properly written.

hacing all tutorials etc. arranged in one place sounds great! I think we like having multiple links from different sections, to make sure that people can find what they're interested in (a lab scientist might not look at dev docs, for example). that doean't mean the content can't all be in the same place, just that we'd link to it ffrom many places.

Overall these are good ideas! ⭐️

**Comment by yochannah** [comment]
@Anu-Ranjan yes! :) 

> @yochannah Are we talking about this website? http://intermine.org/tutorials/. Please let me know so that I can contribute.

**Comment by SiSousa** [comment]
@anushkajha hi, i hope you are well, so i would like to mentioned you in my issue but now that it is closed(cause pr was aproved) i couldn't, but i think that would be a good idea  give you credit cause we were talking about the Exercises topics here so that would be a good idea, dont you think? let me know what you think, open to suggestions, sucess, have a great day.

**Comment by SiSousa** [comment]
> @SiSousa
> 
> > ```
> > 1. There can be a training/Tutorial link in the top right corner of Intermine home page, where there is "Biologists, Developers, contacts and resources"  this will help a first time visitor on the site to find it easy familiarizing themselves to the page and also carry out the required activities on Intermine as the will see what will guide them at their first glance at the page. The Hugo mainroad theme can be adopted for this
> > ```
> 
> could you share a demo of the theme? I'm quite fond of the current intermine theme.
> 
> > ```
> > 2. Everything Tutorials, documentation, videos and training can be arranged inside a link (the link created above) and not scattered in different links such as : the Biologists link has the Tutorials and videos but arranged according to the Intermine registries and bluegene apps. Then, the description of each video link and documentation files should be properly written.
> > ```
> 
> hacing all tutorials etc. arranged in one place sounds great! I think we like having multiple links from different sections, to make sure that people can find what they're interested in (a lab scientist might not look at dev docs, for example). that doean't mean the content can't all be in the same place, just that we'd link to it ffrom many places.
> 
> Overall these are good ideas!

hi, i hope you are alright, thanks for the feedback and help, i am very glad to contribute, so can i start to work on these suggestions? sorry if i didnt understand, i am very excited to work in the project, have a great week.

**Comment by enelesmai** [comment]
Some things that can be easily added, and catch user interest:
* Adding quick access to tutorials for beginners.
* Adding a getting started more visual, with examples, to make it readable and easy understandable.
* Changing the layout for documentation to be more attractive, separated in sections and with more examples.

![image](https://user-images.githubusercontent.com/5160907/78513039-7cac5c80-776e-11ea-83de-355bc448382a.png)

**Comment by Officialkome** [comment]
Hello everyone, I just came across this issue for ideas. I have gone through some of the comments and these are really great ideas by everyone. It is exciting to see that we are all thinking in the same lines i.e. the need for the training portal to have a better layout, better organized content and making the portal more accessible. I would drop screenshots from "low-fi" designs I did to show the layout and content organization pattern I would like to suggest.

**### My suggestions:** 

**1. Currently, the user guide and the intermine docs are hosted at readthedocs.io** and not on the portal (Intermine.org/tutorials).

To create uniformity and better experience for users, how about having every doc, tutorial, video, workshop etc in one place ( here - http://intermine.org/tutorials/). That way, If I click on the User-guide, I will be directed to (https://intermine.org/tutorials/biologist/user-guide). And if I wanted to check upcoming or past workshops/training at Intermine, I will be directed to (https://intermine.org/tutorials/workshops). I think it will be easier to link to these resources if they are all in one place, it will also reduce the confusion new users face.


**2. It would be nice if there was a link from Intermine's homepage** (intermine.org) to the tutorial portal (intermine.org/tutorials). The button/link could be within the section shown in the screenshot below so that it is easily accessible and/OR added in the navigation bar:

![image](https://user-images.githubusercontent.com/52891271/78373725-e12ab880-75c2-11ea-880a-f4089a00b5a2.png)

**3. An idea for easy portal accessibility** would be to remove the biologist and developers drop-down lists in the navbar (on Intermine.org) and replace it with a single link to the tutorial portal Landing page (words like Training Portal or Intermine Manual/Documentation could be used in the navbar) but since @yochannah would like to keep the theme, how about we "de-congest" the Navigation bar, it is too crowded in my opinion. 

Changing the biologists and developers drop-downs to single links, that leads directly to some page in the Tutorial portal might be better than having the drop-down lists. 

To explain better:

The **biologists link** could lead to the user-guide on the tutorial portal - intermine.org/tutorials/biologists/user-guide. That is, if everything thing is moved to one place as suggested in 1).

The **developers link** could lead to Intermine developers docs, which would become (intermine.org/tutorials/developers/intermine-doc).  

These are likely the most important documents that users will be checking for most times, It will be a good way to direct them to what is more important easily. If everything is in one place, once a user is directed to the portal, they will also have access to other learning materials available on intermine easily without searching too much for information. 

**Side note** - Currently, the drop-down is not responsive on mobile, takes up the whole screen on click and the links don't go anywhere.

**4. Landing page for Tutorial portal** (https://intermine.org/training) could implement a header and two column layout as shown in my design. Design-inspo is [Mongodb's Manual](https://docs.mongodb.com/manual/) by the way.  All other Pages (Biologists, Developers, Workshops etc) can also follow same design. We could implement a footer on the portal or choose not to.

Please see layout in the design below (Note - these designs are just to show layout and content organization style, I am not a professional designer)

![image](https://user-images.githubusercontent.com/52891271/78423772-a2e3d680-7660-11ea-92e4-cc1d60542e5c.png)

![image](https://user-images.githubusercontent.com/52891271/78423786-c018a500-7660-11ea-8a33-afe28623e4c3.png)

**5. Content Organization** - Grouping contents is the way to go. All contents can be grouped according to: 

Type of user (is the section for biologists or developers)
Type of content (Is the content for Developers or Biologists or Just general "How to" tutorial?)
Similar topics (Contents/topics that are related or similar can also be further grouped)

This can be achieved by dividing tutorial portal into several pages (biologist page, developers page, workshops/training page, Videos Tutorial/Practicals page etc.) and implementing a sidebar on all of them using drop-down lists to arrange their contents. (shown in design screenshot above).

As already suggested in some comments above , reproducing some of the written tutorials in videos will help users whose style of learning is Instructional, practical and visual. Just to add, we could enhance some of the written tutorials by adding more descriptive screen shots  and we could simplify some tutorials entirely by re-writing them.

**Comment by Angelvicks** [comment]
Hello Everyone, I have gone through the different ideas and they are really good. I will like to add the following;
1- There should be a way users can add more tutorials or contact the community to propose ideas directly because people have different ways of learning and have two or more ways could easily help a user to understand the tutorial and stay to the platform he/she is using in our case if the person decided to use the training portal.
2- I think there is too much information on the footer of the page which might be kind of confusing at some point, so arranging them in a meaningful way by providing just the most important and valuable information can be helpful to user and the must be to do research to get more information. In other words the footer page should be made in way that its more interactive and more eye catching so that user can easily see the key word he/she want and the click in it to get more information.
3- Also about the tutorials the fonts for the links are not quite neat which can be arrange easily to encourage more users first and then the tutorials can be divided into videos and text sections still to help users learn faster with methods that works best for them. Another good way, will be to provide sections for beginners, intermediate and advanced learners together with some test, exercises, challenges which can give stars to users at the end if they pass the challenge or test or exercises. This is just to motivate the users to go forward while evaluating their progress themselves.
4- To conclude, the community can have a trained smart chatbot implemented with artificial intelligence that knows all the challenges, exercises, challenges and the tutorials available to be able to help users at any moment of the day especially when the mentors are not available to respond users. The chatbot can be program with frequently asked question to help the user with those answer each time the questions are asked while waiting for the mentor to give a better explanation later.

**Comment by yochannah** [comment]
Hey folks - thanks for all the amazing discussions here. The training portal project is now in progress so I'll close this issue down - but it's been massively useful and will definitely help influence the way the portal is implemented in the future 🚀 y'all are amazing.
