### ISSUE TITLE
Add Outreachy 2020 interns to the contributors list

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#62]
the list of interns and their github handles is here: https://github.com/orgs/intermine/teams/outreachy-interns-2020/members 

In order to add the interns, I think we can just copy the [GSoC 2019 file](https://github.com/intermine/intermine-homepage-2017/blob/master/content/contributors/gsoc2019.md), rename it outreachy-2020, and chance the json entries to match our current crop of interns.

When merged, the contributors will appear here: http://intermine.org/contributors/

**Comment by JackieBinya** [comment]
@yochannah I am failing  to view the data in this link => https://github.com/orgs/intermine/teams/outreachy-interns-2020/members
I am getting the error below in my browser.
![inter-new](https://user-images.githubusercontent.com/50267279/81579955-1938ce80-93ad-11ea-9f55-cc6ee92dd9e9.png)

**Comment by JackieBinya** [comment]
I followed your instructions. In the _~/content/contributors_ directory, I created an _outreachy-2020.md_ file, then copied content from _gsoc-2019.md_ changed the title only otherwise the rest of the content is unchanged. As you can see from the screenshot below, the GSOC 2019 interns precede the Outreachy 2020 interns. I suggest we edit the layouts as well as the logic so as to fix that so as to ensure the interns are arranged in descending order by year possibly.

![int-new](https://user-images.githubusercontent.com/50267279/81581718-661da480-93af-11ea-9f81-c3cabe796a75.png)

**Comment by yochannah** [comment]
For the Outreachy interns - try changing the weight to be a lower number than the GSoC interns. I think that will bring it up higher?
